name: Deploy Frontend

on:
  push:
    branches:
      - frontend

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Build React App
      run: |
        npm ci
        npm run build

    - name: Sync React Build to Root
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FRONTEND_SERVER_USER }}
        password: ${{ secrets.FRONTEND_SERVER_PASS }}
        local-dir: ./dist/
        server-dir: ./                  # Deploys directly into public_html/
