name: Deploy Backend

on:
  push:
    branches:
      - backend

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Sync PHP Code to Subfolder
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.BACKEND_FTP_USER }}
        password: ${{ secrets.BACKEND_FTP_PASS }}
        server-dir: ./               # Deploys into public_html/media/
        local-dir: ./
        exclude: |
          **/.git**
          **/.github**
          **/node_modules/**
          .env
